Create file structure
GSG-CF05/Tasty-Online-Restaurant pull request #2
Opened 2022-03-17 18:52 UTC by AlaaEid-1

the files structure contains 4 files:
1- Home page (HTML and CSS and js)
2-category page (HTML and CSS and js)
3-cart page (html and CSS and js)
4-image file

2022-03-17 20:24 UTC, Rawan-ZA approved these changes
respectful work

2022-03-17 22:44 UTC, ahmedkhilla approved these changes

2022-03-19 14:43 UTC, hussamshahla approved these changes

2022-03-19 15:23 UTC, yaqootturman requested changes
home page is not good way for naming
+ you didn't use camelCase when use capital letter at the beginning of the file name

2022-03-20 07:46 UTC, yaqootturman requested changes
you still have the wrong names 
check all files and folders

2022-03-20 12:55 UTC, yaqootturman approved these changes

2022-03-20 13:02 UTC, merged