add readme file and consiste the details about project and links
GSG-CF05/Tasty-Online-Restaurant pull request #28
Opened 2022-03-19 21:26 UTC by AlaaEid-1

#23

2022-03-20 07:45 UTC, yaqootturman requested changes

2022-03-20 07:45 UTC, yaqootturman commented on README.md
> +### Description of your website:
Description of our** website:

2022-03-20 07:45 UTC, yaqootturman commented on README.md
> +--------------------------------------------------------------------------------
You should add two part:
- User Journey
- How install the app locally

2022-03-21 08:18 UTC, sara219 requested changes

2022-03-21 08:18 UTC, sara219 commented on README.md
> +    Tasty is an online restaurant app that made to make it easier for the customer to order food by showing the menu of the restaurant. In this app, customers can browse the menu, which includes many
remove the space before `Tasty` so that the description appears as a paragraph instead of a code fragment

<img width="1044" alt="Screen Shot 2022-03-21 at 9 18 42 AM" src="https://user-images.githubusercontent.com/47992412/159218787-39d98035-c49c-4519-8114-5ce35cfd7700.png">

2022-03-21 08:18 UTC, sara219 commented on README.md
> +-----------------------------------------------
To make it look better and more organized:
- the title is the first heading 
- add the title without `name of the project`
::: 
# Tasty

- add the GitHub pages link [live link] with the other links or directly with the title 
:::

# [Tasty](https://gsg-cf05.github.io/Online-Restaurant-Team12/)

2022-03-21 08:18 UTC, sara219 commented on README.md
> +------------------------------------------------------
you already have the APIs, add the link to documentation for every API

2022-03-21 09:00 UTC, sara219 approved these changes

2022-03-21 09:00 UTC, ahmedkhilla approved these changes

2022-03-21 09:03 UTC, hussamshahla approved these changes

2022-03-21 09:46 UTC, merged