upload html , css and media query relate #10
GSG-CF05/Tasty-Online-Restaurant pull request #56
Opened 2022-03-22 20:17 UTC by Rawan-ZA

2022-03-22 20:20 UTC, ahmedkhilla submitted a review, later dismissed

2022-03-23 07:43 UTC, sara219 requested changes
[desktop]: This part (our services) needs some modification, it went out of section border

<img width="159" alt="Screen Shot 2022-03-23 at 9 42 00 AM" src="https://user-images.githubusercontent.com/47992412/159648159-24125285-01b4-4418-b0b6-3cfb31ff4150.png">


these lines keep showing while scrolling 

<img width="591" alt="Screen Shot 2022-03-23 at 9 42 16 AM" src="https://user-images.githubusercontent.com/47992412/159648164-5d4f929a-8459-4502-b1a2-c019c56897ad.png">
<img width="591" alt="Screen Shot 2022-03-23 at 9 42 33 AM" src="https://user-images.githubusercontent.com/47992412/159648181-6c84b58e-37ac-4939-8a2b-34208c02548b.png">

2022-03-23 17:57 UTC, AlaaEid-1 approved these changes

2022-03-23 18:16 UTC, sara219 approved these changes

2022-03-23 18:17 UTC, merged